# Generated by Django 5.0.6 on 2024-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocks",
            name="time_to_search",
            field=models.TimeField(default="00:10:00"),
        ),
    ]
