# Generated by Django 5.0.6 on 2024-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0002_stocks_time_to_search"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stocks",
            old_name="Person",
            new_name="person",
        ),
        migrations.AlterField(
            model_name="stocks",
            name="time_to_search",
            field=models.IntegerField(default="1800000"),
        ),
    ]
