# Generated by Django 5.0.6 on 2024-07-15 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0002_stocks_time_alter_stocks_time_to_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocks",
            name="stock_img",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 15, 1, 18, 57, 160388)
            ),
        ),
    ]
