# Generated by Django 5.0.6 on 2024-07-15 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0003_stocks_stock_img_alter_stocks_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocks",
            name="stock_img",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 15, 1, 21, 10, 731645)
            ),
        ),
    ]
