# Generated by Django 5.0.6 on 2024-07-15 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0004_alter_stocks_stock_img_alter_stocks_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocks",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 15, 4, 55, 49, 637869, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
